galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install/configure an [NGINX](https://nginx.org) load balancer for HTTP/HTTPS/TCP/UDP

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial
        - zesty

  galaxy_tags:
    - load-balancing

dependencies: []
