# --- 
# - 
#   ansible.builtin.yum: 
#     name: 
#       - update
#       - apache2
#       - libxml2-dev
#     state: present
#   become: true
#   name: "install apache"
# - 
#   apache2_module: 
#     ignore_configcheck: true
#     name: 
#       - rewrite
#       - proxy
#       - proxy_balancer
#       - proxy_http
#       - headers
#       - lbmethod_bytraffic
#     state: present
#   become: true
#   name: "enable rewrite module"
# - 
#   become: true
#   name: apache2
#   state: present
# - 
#   become: true
#   command: "cp -r  /home/ubuntu/backup/000-default.conf. /etc/apache2/sites-available/"
#   name: "copy 000-default.conf"
# - 
#   become: true
#   name: apache2
#   state: present



# --- 
# - name: "Install apache"
#   become: true
#   ansible.builtin.apt: 
#     name: 
#       - upgrade=dist force_apt=yes
#       - apache2
#       - libxml2-dev
#     state: latest
  #apt:  name=apache2 update_cache=yes state=latest
  
  
# - name: "enable rewrite module"
#   become: true
#   apache2_module: 
#     ignore_configcheck: true
#     name: 
#       - rewrite
#       - proxy
#       - proxy_balancer
#       - proxy_http
#       - headers
#       - lbmethod_bytraffic
#     state: present
  

# # - name: "restart apache2"
# #   become: true
# #   name: apache2
# #   state: present

# - name: "restart apache2"
#   ansible.builtin.service:
#     name: apache2
#     state: restarted

# - name: "copy 000-default.conf"
#   become: true
#   command: "cp -r  /home/ubuntu/backup/000-default.conf. /etc/apache2/sites-available/"
  

# # - name: "restart apache2"
# #   become: true
# #   name: apache2
# #   state: present

# - name: "restart apache2"
#   become: true
#   ansible.builtin.service:
#     name: apache2
#     state: restarted

--- 

- name: Install apache httpd  (state=present is optional)
  become: true
  apt:
    name: apache2
    state: present

- name: Install libxml2-dev
  become: true
  apt:
    name: libxml2-dev
    state: present

# - name: Enable rewrite module
#   apache2_module:
#     become: true
#     state:  present
#     name: rewrite
#     ignore_configcheck: True

- name: enabled mod_rewrite
  become: true
  apache2_module: name=rewrite state=present

# - name: enabled mod_proxy
#   apache2_module:
#   become: true
#   name: proxy
#   state:  present

- name: enabled mod_proxy
  become: true
  apache2_module: name=proxy state=present
  
- name: enabled mod_proxy_balancer
  become: true
  apache2_module: name=proxy_balancer state=present

- name: enabled mod_proxy_http
  become: true
  apache2_module: name=proxy_http state=present

- name: enabled mod_headers
  become: true
  apache2_module: name=headers state=present

- name: enabled mod_lbmethod_bytraffic
  become: true
  apache2_module: name=lbmethod_bytraffic state=present

- name: restart apache2
  become: true
  service: name=apache2 state=restarted

- name: copy default.conf file
  become: true
  command: "cp -r  /home/ubuntu/backup/000-default.conf /etc/apache2/sites-available/"
  


# - apache2_module:
#     become: true
#     state:  present
#     name: proxy_balancer
#     ignore_configcheck: True

# - apache2_module:
#     become: true
#     state:  present
#     name: proxy_http
#     ignore_configcheck: True

# - apache2_module:
#     become: true
#     state:  present
#     name: headers
#     ignore_configcheck: True

# - apache2_module:
#     become: true
#     state:  present
#     name: lbmethod_bytraffic
#     ignore_configcheck: True


