# --- 
# - 
#   ansible.builtin.yum: 
#     name: 
#       - update
#       - apache2
#       - libxml2-dev
#     state: present
#   become: true
#   name: "install apache"
# - 
#   apache2_module: 
#     ignore_configcheck: true
#     name: 
#       - rewrite
#       - proxy
#       - proxy_balancer
#       - proxy_http
#       - headers
#       - lbmethod_bytraffic
#     state: present
#   become: true
#   name: "enable rewrite module"
# - 
#   become: true
#   name: apache2
#   state: present
# - 
#   become: true
#   command: "cp -r  /home/ubuntu/backup/000-default.conf. /etc/apache2/sites-available/"
#   name: "copy 000-default.conf"
# - 
#   become: true
#   name: apache2
#   state: present



# --- 
# - name: "Install apache"
#   become: true
#   ansible.builtin.apt: 
#     name: 
#       - upgrade=dist force_apt=yes
#       - apache2
#       - libxml2-dev
#     state: latest
  #apt:  name=apache2 update_cache=yes state=latest
  
  
# - name: "enable rewrite module"
#   become: true
#   apache2_module: 
#     ignore_configcheck: true
#     name: 
#       - rewrite
#       - proxy
#       - proxy_balancer
#       - proxy_http
#       - headers
#       - lbmethod_bytraffic
#     state: present
  

# # - name: "restart apache2"
# #   become: true
# #   name: apache2
# #   state: present

# - name: "restart apache2"
#   ansible.builtin.service:
#     name: apache2
#     state: restarted

# - name: "copy 000-default.conf"
#   become: true
#   command: "cp -r  /home/ubuntu/backup/000-default.conf. /etc/apache2/sites-available/"
  

# # - name: "restart apache2"
# #   become: true
# #   name: apache2
# #   state: present

# - name: "restart apache2"
#   become: true
#   ansible.builtin.service:
#     name: apache2
#     state: restarted

--- 

- name: Install apache httpd  (state=present is optional)
  become: true
  apt:
    name: apache2
    state: present

- name: Install libxml2-dev
  become: true
  apt:
    name: libxml2-dev
    state: present
# - name: Update repositories cache and install "foo" package
#   apt:
#     name: foo
#     update_cache: yes

# - name: Remove "foo" package
#   apt:
#     name: foo
#     state: absent

# - name: Install the package "foo"
#   apt:
#     name: foo

# - name: Install a list of packages
#   apt:
#     pkg:
#     - foo
#     - foo-tools
