pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
      stage('Test1') {
      steps {
        script {
          sh 'echo "Testing Stage1"'
        }
      }
    }
    }
}