--- 
- 
  hosts: all
- 
  import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml
  name: "Include dynamic variables"
  tags: 
    - always
  tasks:
- 
  hosts: webservers
- 
  import_playbook: ../static-assignments/webservers.yml
  name: "Webserver assignment"

- 
  import_playbook: ../static-assignments/loadbalancers.yml
  name: "Loadbalancers assignment"
  when: load_balancer_is_required
